PUT http://localhost:3000/api/v1/editImage/10
Content-Type: application/json

{
  "judul": "waduh",
  "deskripsi": "dia adalah seorang manusia"
}

###
DELETE http://localhost:3000/api/v1/deleteImage/1

###
GET http://localhost:3000/api/v1/showImage

###
GET http://localhost:3000/api/v1/detailImage/4

